django_movies/accounts/urls.py
from django.urls import path

from accounts.views import SubmittableLoginView, SuccessMessagedLogoutView, SubmittablePasswordChangeView, SignUpView

app_name = 'accounts'

urlpatterns = [
    path('login/', SubmittableLoginView.as_view(), name='login'),
    path('logout/', SuccessMessagedLogoutView.as_view(), name='logout'),
    path('password_change/', SubmittablePasswordChangeView.as_view(), name='password_change'),
    path('sign_up/', SignUpView.as_view(), name='sign_up')
]

django_movies/core/urls.py
from django.urls import path
from core.views import MovieCreateView, MovieUpdateView, MovieDeleteView, MovieListView, MovieDetailView

app_name = 'core'

urlpatterns = [

    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
    path('movie/create', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/movie_confirm_delete/<pk>', MovieDeleteView.as_view(), name='movie_delete')
]

django_movies/django_movies/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import hello, MovieCreateView, MovieUpdateView, MovieDeleteView
# from core.models import
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('core/', include('core.urls', namespace='core')),
    path('hello/', hello),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]

django_movies/accounts/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import CASCADE, Model, OneToOneField, CharField
from django.contrib.auth.models import User

# Create your models here.
class Profile(Model):
    user = OneToOneField(User, on_delete=CASCADE)
    shoes = CharField(max_length=2)

django_movies/core/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from model_utils import Choices

# Create your models here.
AGE_CHOICES = Choices(
    (0, 'kids', 'kids'),
    (1, 'teens', 'teens'),
    (2, 'adults', 'adults'),
    )
# class AgeLimit(models.IntegerChoices):
#     Adult = 18
#     Young = 12
#     Children = 0
#
#
# agelimit = models.IntegerField(choices=AgeLimit.choices, null=True, blank=True)


class Genre(models.Model):
    name = models.CharField(max_length=20, unique=True)
    age_limit = models.IntegerField(choices=AGE_CHOICES, null=True, blank=True)


    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=70)

    class Meta:
        unique_together = ('name', 'surname')
    def __str__(self):
        return f'{self.name} {self.surname}'


class Country(models.Model):
    country = models.CharField(max_length=40, unique=True, null=True)

    class Meta:
        ordering = ['country']

    def __str__(self):
        return self.country


class Movie(models.Model):
    title = models.CharField(max_length=100)
    rating = models.IntegerField(
        null=True, validators=[MaxValueValidator(10), MinValueValidator(1)]
    )
    category = models.CharField(null=True, max_length=100)
    released = models.DateField(null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL)
    director = models.ForeignKey(Director, null=True, on_delete=models.SET_NULL)
    countries = models.ManyToManyField(Country, related_name='movies')
    # user = models.ForeignKey

    class Meta:
        unique_together = ('title', 'released')

    def __str__(self):
        return f"{self.title} from {self.released}"

django_movies/accounts/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, UserCreationForm
)
from django.db.transaction import atomic
from django.forms import CharField, Form, Textarea

from accounts.models import Profile


class SubmittableForm(Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(*self.fields, Submit('submit', 'Submit'))


class SignUpForm(SubmittableForm, UserCreationForm):
    shoes = CharField(
        label='Tell me your shoes size. (for ex. 40)',
        widget=Textarea,
        min_length=1,
    )
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'first_name']

    def save(self, commit=True, *args, **kwargs):
        user = super().save(commit)
        shoes = self.cleaned_data['shoes']
        profile = Profile(shoes=shoes, user=user)
        profile.save()
        return user

class SubmittableAuthenticationForm(SubmittableForm, AuthenticationForm):
    pass

class SubmittablePasswordChangeForm(SubmittableForm, PasswordChangeForm):
    pass

django_movies/core/forms.py
import re
from datetime import date

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
import crispy_forms
from core.models import Genre, Movie
from django.core.exceptions import ValidationError
from django.forms import DateField

class PastMonthField(forms.DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=result.day)


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized')


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = '__all__' # be explicit lepiej pisać stringi w tupli 'title', 'genre' etc. niż all

    title = forms.CharField(validators=[capitalized_validator])
    genre = forms.ModelChoiceField(queryset=Genre.objects.all())
    rating = forms.IntegerField(min_value=1, max_value=10)
    released = PastMonthField()
    description = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('genre'), Column('rating'), Column('released')),
            'director',
            'description',
            'category',
            'countries',
            Submit('submit', 'Submit'),
        )

    def clean_description(self):
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        cleaned = '. '.join(sentence.capitalize() for sentence in sentences)
        return cleaned

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'comedy' and result['rating'] > 5:
            raise ValidationError('The best comedy is worth a 4.')
        return result

django_movies/accounts/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView

from accounts.forms import SubmittableAuthenticationForm, SubmittablePasswordChangeForm, SignUpForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SubmittableLoginView(LoginView):
    form_class = SubmittableAuthenticationForm
    template_name = 'form.html'


class SubmittablePasswordChangeView(PasswordChangeView):
    form_class = SubmittablePasswordChangeForm
    template_name = 'form.html'
    success_url = reverse_lazy('index')

class SuccessMessagedLogoutView(LogoutView):
    def get_next_page(self):
        result = super().get_next_page()
        messages.success(self.request, 'Successfully logged out!')
        return result

class SignUpView(CreateView):
    template_name = 'form.html'
    form_class = SignUpForm
    success_url = reverse_lazy('index')

django_movies/core/views.py
import logging

from django.http import HttpResponse
from django import views
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from core.models import Movie, AGE_CHOICES
from core.forms import MovieForm

logging.basicConfig(filename='log.txt',
                    filemode='w',
                    level=logging.INFO,)
LOGGER = logging.getLogger(__name__)
# Create your views here.
class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

class MovieCreateView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    title = 'Add Movie'
    template_name = 'form.html'
    form_class = MovieForm
    success_url = reverse_lazy('core:movie_list')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided.')
        return super().form_invalid(form)
## w Pythonie 3.8 pójdzie to rozwiązanie(walrus operator - :=):
    # def post(self, request, *args, **kwargs):
    #     result = super().post(request, *args, **kwargs)
    #     if title := request._post.get('title'):
    #         LOGGER.info(f'Successfully added new movie: {title}')
    #     return result
    def post(self, request, *args, **kwargs):
        result = super().post(request, *args, **kwargs)
        title = request.POST.get('title')
        if title:
            LOGGER.info(f"Successfully added new movie: {self.request.POST.get('title')}")
        return result
class MovieListView(ListView):
    template_name = 'movie_list.html'
    model = Movie

class MovieDetailView(DetailView):
    template_name = 'movie_detail.html'
    model = Movie


class MovieUpdateView(StaffRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('core:movie_list')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided.')
        return super().form_invalid(form)


class MovieDeleteView(StaffRequiredMixin, LoginRequiredMixin, DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('core:movie_list')
    def test_func(self):

        return super().test_func() and self.request.user.is_superuser




# class MovieView(ListView):
#     template_name = 'movies.html'
#     model = Movie
    # extra_context = {'movies': Movie.objects.all(), 'limits': AGE_CHOICES}

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(object_list=None, **kwargs)
    #     context['limits'] = AGE_CHOICES
    #     return context








# def movie(request):
#     return render(
#         request,
#         template_name='movies.html',
#         context={'movies': Movie.objects.all(), 'limits': AGE_CHOICES}
#     )

def hello(request):
    LOGGER.info('\nWreszcie coś działa.')
    return render(
        request,
        template_name='hello.html',
        context={'adjectives': ['beautiful', 'cruel', 'wonderful']},
    )

django_movies/django_movies/views.py
from core.views import MovieListView


class IndexView(MovieListView):
    title = 'Welcome to Django Movies!'
    template_name = 'index.html'

django_movies/django_movies/templates/base.html
{% load bootstrap4 %}
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Django Movies</title>
      {% block styles %}{% bootstrap_css %}{% endblock %}
      {% block scripts %}{% bootstrap_javascript jquery='full' %}{% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container fixed">
        <a class="navbar-brand" href="{% url 'index' %}">Django Movies</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="/">
              Home
            </a>
            <div class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                Movies
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'core:movie_list' %}">List</a>
                <a class="dropdown-item" href="{% url 'core:movie_create' %}">Create</a>
              </div>
            </div>
          </div>
          <div class="navbar-nav ml-auto">
            <div class="nav-item dropdown">
              {% if user.is_authenticated %}
                <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                  {% if user.first_name %}Hello, {{ user.first_name }}!
                  {% else %}Hello, {{ user.username }}!{% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                  <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Password change</a>
                </div>
              {% else %}
                <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                  You are not logged in.
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
                  <a class="dropdown-item text-right" href="{% url 'accounts:sign_up' %}">Sign Up!</a>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="jumbotron">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>

</html>

django_movies/django_movies/templates/form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {% bootstrap_form form %}#}
{#        {% buttons %}#}
{#            <input type="submit" value="Submit" class="btn btn-primary">#}
{#        {% endbuttons %}#}
{#    </form>#}
{% endblock %}

django_movies/django_movies/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello world</title>
</head>
<body>
    <h1>Hello my friend...</h1>
    {%  for adjective in adjectives %}
        {% if adjective != 'cruel' %}
            <p>This is a {{ adjective }} world...</p>
        {% endif %}
    {% endfor %}
</body>
</html>

django_movies/django_movies/templates/index.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}

  <ul>
    {% for movie in object_list %}
      <li>{% movie_format movie %}</li>
    {% endfor %}
  </ul>

  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Last
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}